#!/usr/bin/env ruby

require 'rubygems'
require 'json'
require 'pp'

# Export environment variables for AWS CLI here
$debug = false

if ARGV.empty?
  puts "Usage:"
  puts "owssh list - List all environments"
  puts "owssh describe - Show details of instances in all stacks"
  puts "owssh describe [stack] - Show details of a specific stack"
  puts "owssh [stack] [instance] - SSH to an instance in a stack"
  exit
end

$stacks = {}
$instances = {}

stacks_json = JSON.parse(`aws opsworks describe-stacks`)

stacks_json['Stacks'].each do |stack|
  if $debug then puts "Stack Name: #{stack['Name'].gsub(' ','_').downcase}     Stack ID: #{stack['StackId']}" end
  stack_name = stack['Name'].gsub(' ','_').downcase
  $stacks[stack_name.to_s] = stack['StackId']
end

if ARGV[0] == "list" then
  puts "    --- Stacks ---"
  $stacks.each do |stack_name, id|
    puts "Name: #{stack_name}      ID: #{id}"
  end
  exit
elsif ARGV[0] == "describe" && ARGV[1].nil? then
  $stacks.each do |stack_name, id|
    puts "Stack: #{stack_name}    ID: #{id}"
    instances_json = JSON.parse(`aws opsworks describe-instances --stack-id #{id}`)
    instances_json['Instances'].each do |instance|
      ip = instance['ElasticIp'] || instance['PublicIp']
      puts "Name: #{instance['Hostname']}  IP: #{ip}"
    end
  end
  exit
elsif ARGV[0] == "describe" && !ARGV[1].nil? then
  stack_arg = ARGV[1]
  if $stacks.has_key?(ARGV[1].downcase.to_s) then
    if $debug then puts "Stack ID: #{$stacks[stack_arg]}" end
    puts "Getting data for Stack: #{stack_arg}"
    instances_json = JSON.parse(`aws opsworks describe-instances --stack-id #{$stacks[stack_arg]}`)
    instances_json['Instances'].each do |instance|
      ip = instance['ElasticIp'] || instance['PublicIp'] || "DOWN"
      puts "Name: #{instance['Hostname']}  IP: #{ip}"
    end
  elsif
    puts "Unable to find stack named '#{ARGV[1]}'"
    exit
  end
elsif $stacks.has_key?(ARGV[0].downcase.to_s) then
  if ARGV[1].nil? then
    puts "Please enter an instance name. I.E. rails-app3"
    exit
  end
  stack_arg = ARGV[0].downcase
  instances_json = JSON.parse(`aws opsworks describe-instances --stack-id #{$stacks[stack_arg]}`)
  instances_json['Instances'].each do |instance|
    $instances["#{instance["Hostname"]}"] = instance["PublicIp"]
  end
  if $instances.has_key?(ARGV[1]) then
    puts "Opening connection to #{ARGV[1]}..."
    exec("ssh -i ~/.ssh/id_rsa_dev ubuntu@#{$instances[ARGV[1].to_s]}")
  else
    puts "Instance with name '#{ARGV[1]}' not found"
    exit
  end
else
  puts "I don't quite understand what you're asking me to do..."
  puts " Try running owssh with no arguments for help!"
  exit
end
